# Generated by Django 5.0.2 on 2024-03-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0001_initial'),
        ('travelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travelapi.package'),
        ),
    ]
