# Generated by Django 5.0.2 on 2024-03-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0003_remove_booking_name_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
    ]
