# Generated by Django 5.0.2 on 2024-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0004_rename_description_booking_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
