# Generated by Django 5.0.2 on 2024-03-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0005_alter_booking_first_name'),
        ('travelapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travelapi.activity')),
                ('flight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travelapi.flight')),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travelapi.hotel')),
            ],
        ),
    ]
