# Generated by Django 5.0.2 on 2024-03-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0006_custompackagebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='keshavchapagain97@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
