# Generated by Django 5.0.3 on 2024-03-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='country',
        ),
    ]
