# Generated by Django 5.0.2 on 2024-02-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Suite', 'Suite')], default='Single Room', max_length=20),
        ),
    ]
