# Generated by Django 5.0.3 on 2024-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0002_remove_package_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_hrs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='inclusions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='amenities',
            field=models.CharField(blank=True, default='All-inclusive,Pool,Sauna,Backrooms', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_path',
            field=models.CharField(blank=True, default='quinta.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
