# Generated by Django 5.0.3 on 2024-03-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_api', '0006_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel_api.package')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('flight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel_api.flight')),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel_api.hotel')),
            ],
        ),
    ]
