# Generated by Django 5.0.2 on 2024-03-08 02:03

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='[Flight name]', max_length=200)),
                ('departure_location', models.CharField(default='[Departure Location]', max_length=200)),
                ('arrival_location', models.CharField(default='[Arrival location]', max_length=200)),
                ('departure_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('arrival_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Suite', 'Suite')], default='Single Room', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='[Country]', max_length=70)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('amenities', models.CharField(default='All-inclusive,Pool,Sauna,Backrooms', max_length=100)),
                ('image_path', models.CharField(default='quinta.png', max_length=100)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
        ),
    ]
