# Generated by Django 5.0.3 on 2024-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0003_packagedetails_remove_package_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='[Hotel address]', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='[Hotel description]', max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='[Hotel name]', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
