# Generated by Django 5.0.3 on 2024-03-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0004_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='[default name]', max_length=30),
        ),
    ]
